stages:
  data_ingestion:
    cmd: python src/mice/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mice/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Data_Cortex_Nuclear.xls

  data_validation:
    cmd: python src/mice/pipeline/stage_02_data_validation.py
    deps:
      - src/mice/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/Data_Cortex_Nuclear.xls
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/mice/pipeline/stage_03_data_transformation.py
    deps:
      - src/mice/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/Data_Cortex_Nuclear.xls
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv

  model_trainer:
    cmd: python src/mice/pipeline/stage_04_model_trainer.py
    deps:
      - src/mice/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
    outs:
      - artifacts/model_trainer/model.joblib
  
  model_evaluation:
    cmd: python src/mice/pipeline/stage_05_model_evaluation.py
    deps:
      - src/mice/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/model_trainer/model.joblib
    outs:
      - artifacts/model_evaluation/metrics.json