COLUMNS:
  MouseID: object
  DYRK1A_N: float64
  ITSN1_N: float64
  BDNF_N: float64
  NR1_N: float64
  NR2A_N: float64
  pAKT_N: float64
  pBRAF_N: float64
  pCAMKII_N: float64
  pCREB_N: float64
  pELK_N: float64
  pERK_N: float64
  pJNK_N: float64
  PKCA_N: float64
  pMEK_N: float64
  pNR1_N: float64
  pNR2A_N: float64
  pNR2B_N: float64
  pPKCAB_N: float64
  pRSK_N: float64
  AKT_N: float64
  BRAF_N: float64
  CAMKII_N: float64
  CREB_N: float64
  ELK_N: float64
  ERK_N: float64
  GSK3B_N: float64
  JNK_N: float64
  MEK_N: float64
  TRKA_N: float64
  RSK_N: float64
  APP_N: float64
  Bcatenin_N: float64
  SOD1_N: float64
  MTOR_N: float64
  P38_N: float64
  pMTOR_N: float64
  DSCR1_N: float64
  AMPKA_N: float64
  NR2B_N: float64
  pNUMB_N: float64
  RAPTOR_N: float64
  TIAM1_N: float64
  pP70S6_N: float64
  NUMB_N: float64
  P70S6_N: float64
  pGSK3B_N: float64
  pPKCG_N: float64
  CDK5_N: float64
  S6_N: float64
  ADARB1_N: float64
  AcetylH3K9_N: float64
  RRP1_N: float64
  BAX_N: float64
  ARC_N: float64
  ERBB4_N: float64
  nNOS_N: float64
  Tau_N: float64
  GFAP_N: float64
  GluR3_N: float64
  GluR4_N: float64
  IL1B_N: float64
  P3525_N: float64
  pCASP9_N: float64
  PSD95_N: float64
  SNCA_N: float64
  Ubiquitin_N: float64
  pGSK3B_Tyr216_N: float64
  SHH_N: float64
  BAD_N: float64
  BCL2_N: float64
  pS6_N: float64
  pCFOS_N: float64
  SYP_N: float64
  H3AcK18_N: float64
  EGR1_N: float64
  H3MeK4_N: float64
  CaNA_N: float64
  Genotype: object
  Treatment: object
  Behavior: object
  class: object

TARGET_COLUMN: 
  name: class